<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * An Outage object with all information about one specific outage.
 *
 * @package    auth_outage
 * @author     Daniel Thee Roperto <daniel.roperto@catalyst-au.net>
 * @copyright  Catalyst IT
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace auth_outage;

class outage
{
    /**
     * @var int Outage ID (auto generated by the DB).
     */
    private $id;

    /**
     * @var int Start Time timestamp.
     */
    private $starttime;

    /**
     * @var int Stop Time timestamp.
     */
    private $stoptime;

    /**
     * @var int Amount of minutes before outage starts to show the warning message.
     */
    private $warningminutes;

    /**
     * @var string Short description of the outage (no HTML).
     */
    private $title;

    /**
     * @var string Description of the outage (some HTML allowed).
     */
    private $description;

    /**
     * @var int Moodle User Id that created this outage.
     */
    private $createdby;

    /**
     * @var int Moodle User Id that last modified this outage.
     */
    private $modifiedby;

    /**
     * @var int Timestamp of when this outage was last modified.
     */
    private $lastmodified;

    /**
     * outage constructor.
     * @param $id
     * @param $starttime
     * @param $stoptime
     * @param $warningminutes
     * @param $title
     * @param $description
     * @param $createdby
     * @param $modifiedby
     * @param $lastmodified
     */
    public function __construct($id, $starttime, $stoptime, $warningminutes,
                                $title, $description, $createdby, $modifiedby, $lastmodified) {
        $this->id = $id;
        $this->starttime = $starttime;
        $this->stoptime = $stoptime;
        $this->warningminutes = $warningminutes;
        $this->title = $title;
        $this->description = $description;
        $this->createdby = $createdby;
        $this->modifiedby = $modifiedby;
        $this->lastmodified = $lastmodified;
    }

    /**
     * @return int
     */
    public function get_id() {
        return $this->id;
    }

    /**
     * @return int
     */
    public function get_starttime() {
        return $this->starttime;
    }

    /**
     * @return int
     */
    public function get_stoptime() {
        return $this->stoptime;
    }

    /**
     * @return int
     */
    public function get_warningminutes() {
        return $this->warningminutes;
    }

    /**
     * @return string
     */
    public function get_title() {
        return $this->title;
    }

    /**
     * @return string
     */
    public function get_description() {
        return $this->description;
    }

    /**
     * @return int
     */
    public function get_createdby() {
        return $this->createdby;
    }

    /**
     * @return int
     */
    public function get_modifiedby() {
        return $this->modifiedby;
    }

    /**
     * @return int
     */
    public function get_lastmodified() {
        return $this->lastmodified;
    }
}