<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * An Outage object with all information about one specific outage.
 *
 * @package    auth_outage
 * @author     Daniel Thee Roperto <daniel.roperto@catalyst-au.net>
 * @copyright  Catalyst IT
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace auth_outage\models;

use auth_outage\outagelib;

class outage {
    /**
     * @var int Outage ID (auto generated by the DB).
     */
    public $id = null;

    /**
     * @var int Start Time timestamp.
     */
    public $starttime = null;

    /**
     * @var int Stop Time timestamp.
     */
    public $stoptime = null;

    /**
     * @var int Amount of minutes before outage starts to show the warning message.
     */
    public $warningduration = null;

    /**
     * @var string Short description of the outage (no HTML).
     */
    public $title = null;

    /**
     * @var string Description of the outage (some HTML allowed).
     */
    public $description = null;

    /**
     * @var int Moodle User Id that created this outage.
     */
    public $createdby = null;

    /**
     * @var int Moodle User Id that last modified this outage.
     */
    public $modifiedby = null;

    /**
     * @var int Timestamp of when this outage was last modified.
     */
    public $lastmodified = null;

    /**
     * outage constructor.
     * @param object|array|null The data for the outage.
     */
    public function __construct($data = null) {
        if (is_null($data)) {
            return;
        }

        if (is_object($data) || is_array($data)) {
            outagelib::data2object($data, $this);

            // FIXME types are wrong. Is this behaving as expected?
            foreach (['createdby', 'id', 'lastmodified', 'modifiedby', 'starttime', 'stoptime', 'warningduration']
                     as $f) {
                $this->$f = ($this->$f === null) ? null : (int)$this->$f;
            }

            return;
        }

        throw new \InvalidArgumentException('$data must be null (default), an array or an object.');
    }
}